name: Test node workflow
on:
  [workflow_dispatch]
jobs:
  first:
    name: build-with-node
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: npm install express
      - run: npm install
      - run: docker . -t apulkGIT/rep:latest
      - run: docker push apulkGIT/rep:latest
