name: Test node workflow
on: push
input:
 name: xxxxxxxxxxxxxx
jobs:
  first:
    name: build-with-node
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: npm install express
      - run: npm install
      - run: npm install @actions/core
      - uses: ./
        with:
          name: "asdfaasdf"
      - run: node test.js
